In [18]:
import pandas 
pokemon = pandas.read_csv("Pokemon.csv")

In [19]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [20]:
pokemon["Type 1"].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Rock         44
Electric     44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [21]:
pokemon.sort_values("Defense",ascending=False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
224,208,SteelixMega Steelix,Steel,Ground,610,75,125,230,55,95,30,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
223,208,Steelix,Steel,Ground,510,75,85,200,55,65,30,2,False
414,377,Regirock,Rock,NaN,580,80,100,200,50,100,50,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
488,440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
121,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False

In [22]:
speed_mean = pokemon["Speed"].mean()
def set_speed(inp):
    if inp < speed_mean:
        return "Low speed"
    elif inp == speed_mean:
        return "Fine speed"
    else:
        return "High speed"

In [23]:
pokemon["High_low_speed"] = pokemon["Speed"].apply(set_speed)
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed high low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low speed
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low speed
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High speed
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High speed
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low speed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Low speed
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,High speed
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,High speed
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,High speed
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,High speed

In [25]:
hp_mean = pokemon["HP"].mean()
def set_hp(inph):
    if inph < hp_mean:
        return "Low hp"
    elif inph == hp_mean:
        return "Fine Hp"
    else:
        return "High HP"

In [26]:
pokemon["High_low_HP"] = pokemon["HP"].apply(set_hp)
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Speed high low,High_low_HP
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Low speed,Low hp
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Low speed,Low hp
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,High speed,High HP
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,High speed,High HP
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Low speed,Low hp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Low speed,Low hp
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,High speed,Low hp
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,High speed,High HP
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,High speed,High HP
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,High speed,High HP